# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

"manual: admin":
  - changed-files:
    - any-glob-to-any-file: "admin_manual/**"

"manual: developer":
  - changed-files:
    - any-glob-to-any-file: "developer_manual/**"

"manual: user":
  - changed-files:
    - any-glob-to-any-file: "user_manual/**"

"github_actions":
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**"
