@startuml

package "Nextcloud" {

	node "Base (base.php) (a.k.a init/bootstrap)" as base {
		[init() (include everywhere)] as base_init
		[handleRequest() (used only by index.php)] as base_handleRequest

		[/heartbeat]
		[/disableapp]

		[Session]
		[IUser]
		[SetupFS]
		[OC_Apps (Load Application)] as apps_loader
		[Load Config]
	}

	node "OCS API (REST API) - /ocs/v1.php" as ocs {

	}

	node "Main entry point (Web GUI) - /index.php" {
		[index.php] as index

		node "Routers" as routers {
			[OC_Router]
			[Router (app AppFramwork)]
			[Router (symfony)] #Red
		}

		[OC::Server (server.php)] as oc_server

		node "File View API (View.php)" as viewapi #Red {
			[View.php (deprectated)]
			[Trashbin.php (deprectated)]
			[OC_***.php (deprectated)]
		}

		node "AppFramwork" as appframework {

			[server.php] as server

			node "Files/Node API" as filenodeapi {
				[Modern API to manipulate users' files]
				package "Interfaces" {
					[IRootFolder]
					[IFolder]
					[IFile]
					["..."]
				}
			}

			node "DB" as db {
				[Entity]
				[Mapper]
			}
		}

		node "Storage API" as storageapi {
			[IStorage]
			[IScanner]
			[ICache]
			[IMountPoint]
			[IWatcher]
			[IUpdater]
			["..."]
		}

		node "Hooks" as hooks {
			node "OC_Hooks" as oc_hooks #Red {

			}

			node "Emitter" as emitter #Red {

			}

			node "EventDispatcher" as eventdispatcher {
			}
		}

		index --> base_init
		index --> base_handleRequest
		index --> oc_server
		oc_server --> viewapi
		oc_server --> hooks
		viewapi --> storageapi
		filenodeapi --> storageapi
		oc_server --> server
		server --> filenodeapi
		server --> apps
	}

	node "DAV API - /remote.php" {
		[remote.php] as remote

		[server.php] as davserver

		[Sabre DAV] as sabredav

		package "DAV extensions" as davplugins {
			[File]
			[Chunk upload]
			[Bundle upload]
			[System tags]
		}

		package "Sabre File API" as sabrefile {

		}

		sabrefile --> viewapi
		remote --> davserver
		filenodeapi --> viewapi
		davserver --> sabredav
		sabredav --> davplugins
		davplugins --> sabrefile
	}
}

package Application as apps {

	package "./appinfo" as appinfo {
		[info.xml]
		[routes.php]
	}

	package "./lib" as lib {
		package "./Controller" {
			package "./...Controller" {
				[Files used to render views in the browser]
			}
		}
	}

	package "./src" as src {

	}

	package "./l10n" as l10n {

	}
}

@enduml
