name: 'Sphinx Lint'

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

permissions:
  contents: read

jobs:
  sphinx-lint:
    name: Lint RST files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install sphinx-lint
        run: pip install sphinx-lint

      - name: Run sphinx-lint
        run: sphinx-lint --disable trailing-whitespace --disable horizontal-tab admin_manual developer_manual user_manual
